// {
//       id: "1",
//       title: "React & TypeScript Workshop",
//       type: "Workshop",
//       date: "Saturday, Sep 7, 2:00 PM",
//       location: "Community Tech Center, Downtown",
//       host: "Sarah Chen",
//       image: meetup,
//       attendees: 24,
//       maxAttendees: 30,
//       description: "Learn modern React development with TypeScript in this hands-on workshop. Perfect for developers who want to level up their skills and build better applications.",
//       isJoined: false
//     }

export const eventsData = [
  {
    "id": 1,
    "title": "Community Yoga Session",
    "type": "Fitness",
    "date": "2025-08-20",
    "location": "Bangalore",
    "host": "Yoga with Anu",
    "description": "Join us for a peaceful yoga session in Cubbon Park.",
    "image": "/yoga.png",
    "attendees": 25,
    "maxAttendees": 40,
    "isJoined": false
  },
  {
    "id": 2,
    "title": "Beginner Guitar Workshop",
    "type": "Music",
    "date": "2025-08-22",
    "location": "Mumbai",
    "host": "Strings Academy",
    "description": "Learn the basics of guitar playing with hands-on guidance.",
    "image": "music-event.jpg",
    "attendees": 15,
    "maxAttendees": 60,
    "isJoined": true
  },
  {
    "id": 3,
    "title": "Startup Networking Meetup",
    "type": "Meetup",
    "date": "2025-08-25",
    "location": "Delhi",
    "host": "Delhi Entrepreneurs Club",
    "description": "Meet fellow entrepreneurs, pitch ideas, and network.",
    "image": "/meetup-event.jpg",
    "attendees": 50,
    "maxAttendees": 120,
    "isJoined": true
  },
  {
    "id": 4,
    "title": "Digital Marketing Seminar",
    "type": "Workshop",
    "date": "2025-08-28",
    "location": "Hyderabad",
    "host": "Marketing Gurus",
    "description": "Learn the latest trends and strategies in digital marketing.",
    "image": "workshop-event.jpg",
    "attendees": 75,
    "maxAttendees": 300,
    "isJoined": true
  },
  {
    "id": 5,
    "title": "Weekend Trek to Nandi Hills",
    "type": "Sports",
    "date": "2025-08-30",
    "location": "Bangalore",
    "host": "Adventure Trails",
    "description": "An early morning trek to Nandi Hills followed by breakfast.",
    "image": "/sports-event.jpg",
    "attendees": 250,
    "maxAttendees": 320,
    "isJoined": false
  },
  {
    "id": 6,
    "title": "Art & Craft for Kids",
    "type": "Workshop",
    "date": "2025-09-01",
    "location": "Pune",
    "host": "Creative Hands",
    "description": "Fun and educational art activities for children aged 6–12.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrtCdnhhPFpSKXCKGCiyNJovbFZEOSSegfyA&s",
    "attendees": 25,
    "maxAttendees": 175,
    "isJoined": false
  },
  {
    "id": 7,
    "title": "City Photography Walk",
    "type": "Meetup",
    "date": "2025-09-03",
    "location": "Chennai",
    "host": "Lens Lovers Club",
    "description": "Explore the city while improving your photography skills.",
    "image": "https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2023/10/photo-walk-photography-6.jpg",
    "attendees":60,
    "maxAttendees": 130,
    "isJoined": false
  },
  {
    "id": 8,
    "title": "Cooking Masterclass: Italian Cuisine",
    "type": "Workshop",
    "date": "2025-09-05",
    "location": "Kolkata",
    "host": "Chef Maria",
    "description": "Learn to cook authentic Italian dishes from scratch.",
    "image": "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/10/28/58/bb.jpg",
    "attendees": 12,
    "maxAttendees": 25,
    "isJoined": false
  },
  {
    "id": 9,
    "title": "Live Jazz Night",
    "type": "Music",
    "date": "2025-09-07",
    "location": "Goa",
    "host": "Goa Jazz Club",
    "description": "An evening of live jazz performances by local musicians.",
    "image": "music-kids.jpg",
    "attendees": 25,
    "maxAttendees": 60,
    "isJoined": true
  },
  {
    "id": 10,
    "title": "Community Beach Cleanup",
    "type": "Social",
    "date": "2025-09-10",
    "location": "Mumbai",
    "host": "Eco Warriors",
    "description": "Join us in cleaning up Juhu Beach and making a difference.",
    "image": "https://growbilliontrees.com/cdn/shop/files/iStock-472102653-beach-cleaning.jpg",
    "attendees": 49,
    "maxAttendees": 55,
    "isJoined": false
  },
  {
    "id": 11,
    "title": "Stand-up Comedy Night",
    "type": "Entertainment",
    "date": "2025-09-12",
    "location": "Bangalore",
    "host": "Laugh Out Loud",
    "description": "A night full of laughter with top stand-up comedians.",
    "image": "https://res.cloudinary.com/dwzmsvp7f/image/upload/f_auto,w_1280/c_crop%2Cg_custom%2Fv1754813606%2Fuo7bducrdeipowieg9do.jpg",
    "attendees": 25,
    "maxAttendees": 100,
    "isJoined": false
  },
  {
    "id": 12,
    "title": "Chess Tournament",
    "type": "Sports",
    "date": "2025-09-14",
    "location": "Delhi",
    "host": "Delhi Chess Club",
    "description": "Compete with fellow chess enthusiasts for exciting prizes.",
    "image": "https://images.chesscomfiles.com/uploads/v1/article/24124.1cdd3505.668x375o.cecda757820f@2x.jpeg",
    "attendees": 28,
    "maxAttendees": 50,
    "isJoined": false
  },
  {
    "id": 13,
    "title": "Mindfulness Meditation Retreat",
    "type": "Fitness",
    "date": "2025-09-16",
    "location": "Rishikesh",
    "host": "Peaceful Minds",
    "description": "A weekend retreat to practice mindfulness and meditation.",
    "image": "https://i0.wp.com/mindful.me.uk/wp-content/uploads/2019/07/Meditation-Retreat.jpg",
    "attendees": 152,
    "maxAttendees": 160,
    "isJoined": true
  },
  {
    "id": 14,
    "title": "Blockchain for Beginners",
    "type": "Workshop",
    "date": "2025-09-18",
    "location": "Pune",
    "host": "TechLearn Hub",
    "description": "Understand the basics of blockchain and its applications.",
    "image": "https://tech-gyan.in/wp-content/uploads/2021/01/Blockchain-for-Beginners.jpg",
    "attendees": 250,
    "maxAttendees": 300,
    "isJoined": false
  },
  {
    "id": 15,
    "title": "Bird Watching Morning",
    "type": "Meetup",
    "date": "2025-09-20",
    "location": "Jaipur",
    "host": "Nature Explorers",
    "description": "Join us to spot and learn about local bird species.",
    "image": "https://culturalsafaritours.com/wp-content/uploads/2018/10/mtkangchenjungatour.jpg",
    "attendees": 25,
    "maxAttendees": 30,
    "isJoined": false
  },
  {
    "id": 16,
    "title": "Poetry Open Mic",
    "type": "Entertainment",
    "date": "2025-09-22",
    "location": "Chandigarh",
    "host": "Words & Verses",
    "description": "An evening for poets to share their work with the community.",
    "image": "https://i.ytimg.com/vi/dFUPkg2Z2qs/maxresdefault.jpg",
    "attendees": 10,
    "maxAttendees": 30,
    "isJoined": false
  },
  {
    "id": 17,
    "title": "DIY Home Gardening Workshop",
    "type": "Workshop",
    "date": "2025-09-24",
    "location": "Ahmedabad",
    "host": "Green Thumbs",
    "description": "Learn how to start and maintain your own home garden.",
    "image": "https://www.mynaturefirst.com/images/about/w6.jpg",
    "attendees": 25,
    "maxAttendees": 70,
    "isJoined": true
  },
  {
    "id": 18,
    "title": "Marathon for Charity",
    "type": "Sports",
    "date": "2025-09-26",
    "location": "Kochi",
    "host": "Run for Cause",
    "description": "Participate in a marathon to raise funds for charity.",
    "image": "https://www.mccourtfoundation.org/wp-content/uploads/2023/06/KF2_3143-Charity-half-Header-Image-1.jpg",
    "attendees": 250,
    "maxAttendees": 300,
    "isJoined": false
  },
  {
    "id": 19,
    "title": "Language Exchange Meetup",
    "type": "Meetup",
    "date": "2025-09-28",
    "location": "Bangalore",
    "host": "Global Friends",
    "description": "Practice languages and make friends from different cultures.",
    "image": "https://englishonlycafe.com/wp-content/uploads/pic/cafe/lx/352.jpg",
    "attendees": 25,
    "maxAttendees": 40,
    "isJoined": true
  },
  {
    "id": 20,
    "title": "Film Screening: Indie Shorts",
    "type": "Entertainment",
    "date": "2025-09-30",
    "location": "Mumbai",
    "host": "Cinephiles Club",
    "description": "An evening of short films by independent filmmakers.",
    "image": "https://cms.indieshortsmag.com/wp-content/uploads/2025/06/Vancouver-Short-Film-Festival-2025-Nominations-Unveiled-Indie-Shorts-Mag.jpg",
    "attendees": 25,
    "maxAttendees": 30,
    "isJoined": false
  },
]